#############################################
# Wikimedia SVGO config as defined in
# https://phabricator.wikimedia.org/T178867
#
# All properties are listed. WMF specific ones
# have been explicitly set to true or false.
#############################################

multipass: false
full: false

plugins:
  - removeDoctype: false
  - removeXMLProcInst: false
  - removeComments: false
  - removeMetadata: false
  - removeXMLNS: false
  - removeEditorsNSData: false
  - cleanupAttrs: false
  - inlineStyles: false
  - minifyStyles: false
  - convertStyleToAttrs: false
  - cleanupIDs: false
  - prefixIds: false
  - removeRasterImages: false
  - removeUselessDefs: false
  - cleanupNumericValues: false
  - cleanupListOfValues: false
  - convertColors: false
  - removeUnknownsAndDefaults: false
  - removeNonInheritableGroupAttrs: false
  - removeUselessStrokeAndFill: false
  - removeViewBox: false
  - cleanupEnableBackground: false
  - removeHiddenElems: false
  - removeEmptyText: false
  - convertShapeToPath: false
  - convertEllipseToCircle: false
  - moveElemsAttrsToGroup: false
  - moveGroupAttrsToElems: false
  - collapseGroups: false
  - convertPathData: false
  - convertTransform: false
  - removeEmptyAttrs: false
  - removeEmptyContainers: false
  - mergePaths: false
  - removeUnusedNS: false
  - sortAttrs: false
  - sortDefsChildren: false
  - removeTitle: false
  - removeDesc: false
  - removeDimensions: false
  - removeAttrs: false
  - removeAttributesBySelector: false
  - removeElementsByAttr: false
  - addClassesToSVGElement: false
  - removeStyleElement: false
  - removeScriptElement: false
  - addAttributesToSVGElement: false
  - removeOffCanvasPaths: false
  - reusePaths: false

js2svg:
  pretty: true
  indent: ' '
